# Generated by Django 2.1.1 on 2019-01-21 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sign', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateField(default=datetime.date(2019, 1, 21)),
        ),
    ]
