# Generated by Django 2.1.1 on 2019-01-11 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 10, 35, 58, 719694)),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='inflow',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='outflow',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
