# Generated by Django 2.1.1 on 2019-03-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_category_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='currency',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
