# Generated by Django 2.1.5 on 2019-01-14 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_auto_20190111_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 14, 23, 21, 9, 844099)),
        ),
    ]
