# Generated by Django 2.1.1 on 2019-03-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_auto_20190326_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='inflow',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='outflow',
        ),
    ]
