# Generated by Django 2.1.1 on 2019-01-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_auto_20190121_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='ios',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
