# Generated by Django 2.1.5 on 2019-02-02 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_currency_ios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 2, 21, 14, 35, 761022)),
        ),
    ]
